#!/usr/bin/env python3
"""G3 / step 1 — outcome-label variance decomposition on the CL-073 training corpus.

Reads ONLY the `values` (+ `aux_mask`, `group_id`) arrays out of the 2,400 per-game
`.npz` files of `distill_strong_20260723/iter_00..03` — the exact corpus
`measurement/value_unlock_20260730/READOUT.md` §2 names (2,400 files / 345,333 rows,
generated by the net-free champion at k8x1376 = 11,008 sims/move).

Pure arithmetic: no engine, no search, no net forward, no GPU.

The label is `values = tanh((p0-p1)/15)` backfilled from the FINAL score, oriented to
the MOVER (`gen_fair_distill.py:319-320`, corroborated by the corpus manifest's
`value_target_desc`).  So per game g the label takes exactly two values, +c_g and
-c_g, and which one a row gets is decided solely by whose turn it is.  The
decomposition below measures that directly rather than assuming it.

Levels:
  L0  grand           (all rows)
  L1  game            (one .npz = one game)
  L2  game x side     (game crossed with the sign of the mover-POV label)
  L3  row             (position / decision point)

Output: JSON on stdout / --out.
"""
from __future__ import annotations

import argparse
import concurrent.futures as cf
import glob
import hashlib
import json
import os
import subprocess
import sys
import time

import numpy as np

CORPUS = "/mnt/c/carc-shared/distill_strong_20260723"
ITERS = ["iter_00", "iter_01", "iter_02", "iter_03"]


def scan_one(path: str) -> dict:
    with np.load(path) as d:
        v = np.asarray(d["values"], dtype=np.float64)
        aux = np.asarray(d["aux_mask"])
        gid = np.asarray(d["group_id"])
    absv = np.abs(v)
    return {
        "path": path,
        "n": int(v.size),
        "sum": float(v.sum()),
        "sumsq": float((v * v).sum()),
        "abs_min": float(absv.min()),
        "abs_max": float(absv.max()),
        "abs_mean": float(absv.mean()),
        "n_pos": int((v > 0).sum()),
        "n_neg": int((v < 0).sum()),
        "n_zero": int((v == 0).sum()),
        "n_uniq_abs": int(np.unique(absv).size),
        "n_aux_true": int(aux.sum()),
        "gid_min": int(gid.min()),
        "gid_max": int(gid.max()),
        # within-(game x side) sums, for the L2 decomposition
        "pos_sum": float(v[v > 0].sum()),
        "pos_sumsq": float((v[v > 0] ** 2).sum()),
        "neg_sum": float(v[v < 0].sum()),
        "neg_sumsq": float((v[v < 0] ** 2).sum()),
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=None)
    ap.add_argument("--workers", type=int, default=8)
    args = ap.parse_args()

    files = []
    for it in ITERS:
        files += sorted(glob.glob(os.path.join(CORPUS, it, "*.npz")))
    t0 = time.time()
    with cf.ThreadPoolExecutor(max_workers=args.workers) as ex:
        recs = list(ex.map(scan_one, files))
    wall = time.time() - t0

    n_rows = sum(r["n"] for r in recs)
    n_games = len(recs)

    # ---- L0: grand variance of the mover-POV label -------------------------
    S = sum(r["sum"] for r in recs)
    SS = sum(r["sumsq"] for r in recs)
    grand_mean = S / n_rows
    var_total = SS / n_rows - grand_mean ** 2

    # ---- L1: between-game / within-game ------------------------------------
    ss_between_game = 0.0
    ss_within_game = 0.0
    for r in recs:
        m = r["sum"] / r["n"]
        ss_between_game += r["n"] * (m - grand_mean) ** 2
        ss_within_game += r["sumsq"] - r["n"] * m * m
    ss_total = SS - n_rows * grand_mean ** 2

    # ---- L2: between-(game x side) / within-(game x side) ------------------
    ss_between_gs = 0.0
    ss_within_gs = 0.0
    n_cells = 0
    for r in recs:
        for np_, s_, ssq_ in (
            (r["n_pos"], r["pos_sum"], r["pos_sumsq"]),
            (r["n_neg"], r["neg_sum"], r["neg_sumsq"]),
        ):
            if np_ == 0:
                continue
            n_cells += 1
            m = s_ / np_
            ss_between_gs += np_ * (m - grand_mean) ** 2
            ss_within_gs += ssq_ - np_ * m * m

    # ---- the |label| check: is the label constant within a game? -----------
    max_abs_range = max(r["abs_max"] - r["abs_min"] for r in recs)
    n_games_multi_abs = sum(1 for r in recs if r["n_uniq_abs"] != 1)
    per_game_c = np.array([r["abs_mean"] for r in recs])

    # ---- sibling structure present in the corpus? --------------------------
    gid_lo = min(r["gid_min"] for r in recs)
    gid_hi = max(r["gid_max"] for r in recs)

    def frac(x):
        return float(x / ss_total) if ss_total else float("nan")

    out = {
        "kind": "g3_corpus_outcome_label_decomposition",
        "generated_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "code_rev": subprocess.run(
            ["git", "-C", "/home/doctor/projects/carcassone", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True).stdout.strip(),
        "inputs": {
            "corpus_root": CORPUS,
            "iters": ITERS,
            "n_files": n_games,
            "file_list_sha256": hashlib.sha256(
                "\n".join(os.path.basename(f) for f in files).encode()).hexdigest(),
            "label_definition": "values = tanh((p0-p1)/15), mover-POV, backfilled from the FINAL score "
                                "(scripts/distill_flywheel/gen_fair_distill.py:319-320; corpus manifest "
                                "config.value_target_desc)",
            "manifest": os.path.join(CORPUS, "iter_00", "manifest.json"),
        },
        "counts": {
            "n_games": n_games,
            "n_rows": int(n_rows),
            "rows_per_game_mean": n_rows / n_games,
            "n_game_x_side_cells": n_cells,
            "n_aux_true_rows": int(sum(r["n_aux_true"] for r in recs)),
            "n_zero_label_rows": int(sum(r["n_zero"] for r in recs)),
        },
        "label_moments_all_rows": {
            "mean": grand_mean,
            "var": var_total,
            "sd": float(np.sqrt(var_total)),
            "readout_reference_sd": 0.711358,
        },
        "within_game_label_constancy": {
            "max_within_game_range_of_abs_label": max_abs_range,
            "n_games_with_more_than_one_abs_label": n_games_multi_abs,
            "per_game_abs_label_mean": float(per_game_c.mean()),
            "per_game_abs_label_sd": float(per_game_c.std(ddof=0)),
            "per_game_abs_label_min": float(per_game_c.min()),
            "per_game_abs_label_max": float(per_game_c.max()),
        },
        "sibling_structure_in_corpus": {
            "group_id_min": gid_lo,
            "group_id_max": gid_hi,
            "note": "group_id is -1 on every row: the corpus stores ONE row per decision "
                    "(the played move's resulting position), never the sibling set. "
                    "There is no within-sibling level in the training data at all.",
        },
        "decomposition": {
            "ss_total": ss_total,
            "L1_game": {
                "ss_between": ss_between_game,
                "ss_within": ss_within_game,
                "frac_between": frac(ss_between_game),
                "frac_within": frac(ss_within_game),
            },
            "L2_game_x_side": {
                "ss_between": ss_between_gs,
                "ss_within": ss_within_gs,
                "frac_between": frac(ss_between_gs),
                "frac_within": frac(ss_within_gs),
                "note": "within-(game x side) SS is the variance left at the POSITION level "
                        "once the game and the side-to-move are known.",
            },
        },
        "wall_secs": wall,
    }
    js = json.dumps(out, indent=2)
    if args.out:
        with open(args.out, "w") as fh:
            fh.write(js + "\n")
    print(js)


if __name__ == "__main__":
    main()
