"""4.1 — Expert-position suite builder + renderer + scorer.

Produces a JSONL "expert suite" of 200-500 Carcassonne positions for two uses:
  1. HUMAN-ANCHOR: sit a strong/expert human at each position, record their move,
     score the regret vs the agent's ground truth (objective at K<=4, search-
     labeled midgame).
  2. ANALYZER VALIDATION: this SAME suite is the Phase-5 analyzer's held-out set
     (a move-quality analyzer must reproduce the exact/search regret ranking).

Two kinds of position, one record schema (`exact` flags which):
  (a) ENDGAME (exact=True): K<=4 roots carrying the exact-solver `child_values`
      (endgame_solver.solve). Objective per-action values => objective regret.
      * K=2 (150 roots) come FREE from the on-disk solver cache
        measurement/pre_tool_audit/k2_childvalues.jsonl (no solve needed).
      * K=3/4 are generated by CALLING solve() on replayable source games
        (l23_k4_multisource.jsonl / l23_positions.jsonl). That is CPU-heavy and
        is GUARDED behind --run-solver ("needs boxes"); resumable per gen_id.
  (b) MIDGAME (exact=False): stratified positions (farm fights, meeple scarcity,
      merges/closure races, generic) labeled by the STRONGEST available search
      (champion clairvoyant HeuristicMCTS @ h6400) -> best move + per-action root
      Q. Flagged non-exact. Search labeling is also GUARDED (heavy).

Record schema (one JSON object per line):
  {
    "id": "k2_g3200000000_p140",
    "provenance": {"deck_seed": int, "ply": int, "replay": "greedy"|"actions",
                   "actions": [int...]?, "source": str},
    "stratum": "endgame_k2" | "farm_fight" | "meeple_scarcity" |
               "closure_race" | "midgame_generic",
    "k_remaining": int, "to_move": int, "phase": "tiles"|"meeples",
    "in_hand_tile": str|None, "scores": [int,int],
    "exact": bool,
    "child_values": {action_id(str): value},   # exact only (P0-perspective)
    "optimal_actions": [int...],                # exact only
    "vstar": float,                             # exact only
    "best_move": int,                           # both (label / an optimal action)
    "label": {"agent": str, "sims": int, "child_q": {aid:str: q}}|None,  # midgame
    "legal_moves": [int...]
  }

Usage:
  # prove the pipeline (RUNS: builds 3 exact + 2 midgame, renders, scores fake human):
  .venv/bin/python scripts/human_anchor/build_suite.py --self-test

  # cheap exact suite from the on-disk K=2 cache (no solver, no boxes):
  .venv/bin/python scripts/human_anchor/build_suite.py --from-cache --out measurement/human_anchor/suite.jsonl

  # HEAVY (needs boxes): solve K=3/4 endgames + label midgames
  .venv/bin/python scripts/human_anchor/build_suite.py --generate --run-solver --ks 3 4 --out ...
  .venv/bin/python scripts/human_anchor/build_suite.py --render --suite S.jsonl
  .venv/bin/python scripts/human_anchor/build_suite.py --score --suite S.jsonl --choices human.json
"""
from __future__ import annotations

import env_preamble  # noqa: F401  MUST precede carcassonne_ai import
import argparse
import json
import sys
from pathlib import Path

import _common as C

K2_CACHE = C.REPO_ROOT / "measurement/pre_tool_audit/k2_childvalues.jsonl"
L23_POS = C.REPO_ROOT / "measurement/level2/l23_positions.jsonl"
L23_K4 = C.REPO_ROOT / "measurement/level2/l23_k4_multisource.jsonl"

# The exact solver's ground-truth mode. Marginalized = honest hidden-bag value
# (the PREFERRED L2-3 ground truth); tractable only at K<=2 without alpha-beta.
# For K>=3 we score the CLAIRVOYANT optimum (alpha-beta), which matches what a
# clairvoyant search agent targets — flagged in the record's `solve_mode`.
DEFAULT_BUDGET = 4_000_000


# --------------------------------------------------------------------------- #
# stratification
# --------------------------------------------------------------------------- #
def classify_stratum(state) -> str:
    """Heuristic tag for a MIDGAME position. Proxies (documented in README):
      meeple_scarcity : a side has <=1 free meeple (scoring is now a tempo fight)
      farm_fight      : >=3 farmers already committed on the board (endgame farms)
      closure_race    : late (>=100 tiles placed) and someone still holds an open
                        city meeple (a race to close before the bag empties)
      midgame_generic : none of the above.
    K<=4 positions are tagged endgame_k{K} upstream, not here."""
    from wingedsheep.carcassonne.objects.meeple_type import MeepleType
    free = list(state.meeples)  # free meeples per player
    if min(free) <= 1:
        return "meeple_scarcity"
    farmers = sum(
        1 for pl in range(state.players) for mp in state.placed_meeples[pl]
        if mp.meeple_type in (MeepleType.FARMER, MeepleType.BIG_FARMER)
    )
    if farmers >= 3:
        return "farm_fight"
    placed = len(getattr(state, "placed_coords", []))
    normals = sum(
        1 for pl in range(state.players) for mp in state.placed_meeples[pl]
        if mp.meeple_type in (MeepleType.NORMAL, MeepleType.BIG)
    )
    if placed >= 100 and normals >= 1:
        return "closure_race"
    return "midgame_generic"


# --------------------------------------------------------------------------- #
# (a) EXACT endgame records
# --------------------------------------------------------------------------- #
def build_exact_from_cache(limit: int | None = None) -> list[dict]:
    """Turn the on-disk K=2 solver cache into suite records. NO solve, NO boxes.
    Reconstructs each board (greedy replay) to recompute legal moves + validate
    that the cached child_values cover exactly the legal set. Position metadata
    (in_hand_tile, scores, phase) is read off the RECONSTRUCTED board — the
    authoritative source — not the l23 meta (which has one row per K per game)."""
    if not K2_CACHE.exists():
        raise FileNotFoundError(f"K=2 solver cache missing: {K2_CACHE}")
    recs = []
    for line in K2_CACHE.read_text().splitlines():
        if not line.strip():
            continue
        o = json.loads(line)
        gid, seed, ply = o["gen_id"], int(o["seed"]), int(o["ply"])
        # prefer the marginalized ground truth; fall back to clairvoyant.
        gt = o.get("marginalized") or o.get("clairvoyant")
        cv = {str(k): float(v) for k, v in gt["child_values"].items()}
        prov = {"deck_seed": seed, "ply": ply, "replay": "greedy",
                "source": "greedy_selfplay"}
        game, board = C.reconstruct(prov)
        legal = set(C.legal_action_ids(game, board))
        cv_keys = {int(k) for k in cv}
        # sanity: cached actions must be a subset of the reconstructed legal set
        if not cv_keys.issubset(legal):
            print(f"  [skip] {gid}: cached child_values not subset of legal set "
                  f"(cache offset mismatch) — {len(cv_keys - legal)} stray", file=sys.stderr)
            continue
        st = board.state
        in_hand = st.next_tile.description if st.next_tile is not None else None
        recs.append({
            "id": f"k2_{gid}_p{ply}",
            "provenance": prov,
            "stratum": f"endgame_k{o['k_remaining']}",
            "k_remaining": int(o["k_remaining"]),
            "to_move": int(gt["to_move"]),
            "phase": st.phase.value,
            "in_hand_tile": in_hand,
            "scores": list(st.scores),
            "exact": True,
            "solve_mode": "marginalized" if o.get("marginalized") else "clairvoyant",
            "child_values": cv,
            "optimal_actions": [int(a) for a in gt["optimal_actions"]],
            "vstar": float(gt["value"]),
            "best_move": int(min(gt["optimal_actions"])),
            "label": None,
            "legal_moves": sorted(legal),
        })
        if limit and len(recs) >= limit:
            break
    return recs


def solve_position(game, board, mode: str, budget: int = DEFAULT_BUDGET):
    """Thin wrapper over endgame_solver.solve (imported, never edited)."""
    import endgame_solver as S
    ab = (mode == "clairvoyant")
    return S.solve(game, board, mode=mode, budget=budget, alphabeta=ab)


def generate_exact_records(ks=(3, 4), limit=None, budget=DEFAULT_BUDGET,
                           out_path: Path | None = None):
    """HEAVY / NEEDS BOXES. Replay K=3/4 source games (l23_k4_multisource has the
    action sequence -> lossless root_replay), find the first TILES ply at the
    target K, CALL solve(), emit exact records. Resumable: skips gen_ids already
    present in `out_path`."""
    if not L23_K4.exists():
        raise FileNotFoundError(f"K=4 source games missing: {L23_K4}")
    done = set()
    if out_path and Path(out_path).exists():
        for line in Path(out_path).read_text().splitlines():
            if line.strip():
                done.add(json.loads(line)["id"])
    recs = []
    for line in L23_K4.read_text().splitlines():
        if not line.strip():
            continue
        o = json.loads(line)
        k = int(o["k_remaining"])
        if k not in ks:
            continue
        gid, seed, ply = o["gen_id"], int(o["seed"]), int(o["ply"])
        rid = f"k{k}_{gid}_p{ply}"
        if rid in done:
            continue
        prov = {"deck_seed": seed, "ply": ply, "replay": "actions",
                "actions": [int(a) for a in o["actions"]], "source": o.get("source_agent", "greedy")}
        game, board = C.reconstruct(prov)
        mode = "marginalized" if k <= 2 else "clairvoyant"
        res = solve_position(game, board, mode, budget)
        rec = {
            "id": rid, "provenance": prov, "stratum": f"endgame_k{k}",
            "k_remaining": k, "to_move": res.to_move, "phase": board.state.phase.value,
            "in_hand_tile": o.get("in_hand_tile"), "scores": list(board.state.scores),
            "exact": True, "solve_mode": mode,
            "child_values": {str(a): float(v) for a, v in res.child_values.items()},
            "optimal_actions": [int(a) for a in res.optimal_actions],
            "vstar": float(res.value), "best_move": int(min(res.optimal_actions)),
            "label": None, "legal_moves": sorted(res.child_values),
        }
        recs.append(rec)
        if out_path:  # append-as-you-go for resumability
            with Path(out_path).open("a") as fh:
                fh.write(json.dumps(rec) + "\n")
        if limit and len(recs) >= limit:
            break
    return recs


# --------------------------------------------------------------------------- #
# (b) MIDGAME search-labeled records
# --------------------------------------------------------------------------- #
def label_with_search(game, board, sims: int, c_puct: float = 3.0, seed: int = 0):
    """Run clairvoyant HeuristicMCTS and harvest (best_move, per-action root Q).
    Q is signed into the ROOT player's perspective (mirrors fair_agent.pool_root_stats).
    Returns (best_move, child_q dict). HeuristicMCTS is IMPORTED, never edited."""
    from carcassonne_ai.mcts import HeuristicMCTS
    m = HeuristicMCTS(game=game, simulations=int(sims), c=float(c_puct),
                      seed=int(seed), heur_leaf="v2_7", leaf_cfg=None)
    m.search(board)
    root_key = game.string_representation(board)
    root = m._nodes.get(root_key)
    child_q: dict[int, float] = {}
    child_n: dict[int, float] = {}
    seen: set[int] = set()
    for a in sorted(root.children):
        ch = root.children[a]
        if ch.N <= 0 or id(ch) in seen:
            continue
        seen.add(id(ch))
        sw = ch.W if ch.player_to_move == root.player_to_move else -ch.W
        child_q[a] = sw / ch.N
        child_n[a] = ch.N
    m.clear()
    # best = max pooled-Q (>=2 visits), matching the fair agent's pooled-Q rule.
    eligible = [a for a in child_q if child_n[a] >= 2] or list(child_q)
    best = int(max(eligible, key=lambda a: (child_q[a], child_n[a], -a)))
    return best, child_q


def build_midgame_records(source_seeds, ply: int, sims: int, agent_name: str,
                          c_puct: float = 3.0) -> list[dict]:
    """HEAVY / NEEDS BOXES at h6400. Reconstruct a midgame position from each
    greedy game at `ply`, stratify it, label it with search."""
    recs = []
    for seed in source_seeds:
        prov = {"deck_seed": int(seed), "ply": int(ply), "replay": "greedy",
                "source": "greedy_selfplay"}
        game, board = C.reconstruct(prov)
        if C.k_remaining(board.state) <= 4:
            continue  # that's an endgame position; belongs to the exact set
        best, child_q = label_with_search(game, board, sims, c_puct, seed=int(seed))
        st = board.state
        recs.append({
            "id": f"mid_g{seed}_p{ply}",
            "provenance": prov,
            "stratum": classify_stratum(st),
            "k_remaining": C.k_remaining(st),
            "to_move": int(st.current_player),
            "phase": st.phase.value,
            "in_hand_tile": st.next_tile.description if st.next_tile is not None else None,
            "scores": list(st.scores),
            "exact": False,
            "child_values": None,
            "optimal_actions": None,
            "vstar": None,
            "best_move": int(best),
            "label": {"agent": agent_name, "sims": int(sims),
                      "child_q": {str(a): float(q) for a, q in child_q.items()}},
            "legal_moves": C.legal_action_ids(game, board),
        })
    return recs


# --------------------------------------------------------------------------- #
# rendering + scoring
# --------------------------------------------------------------------------- #
def render_suite(suite_path: Path, out=sys.stdout) -> None:
    for line in Path(suite_path).read_text().splitlines():
        if not line.strip():
            continue
        rec = json.loads(line)
        _game, board = C.reconstruct(rec["provenance"])
        print(C.render_position(rec, board), file=out)
        print("-" * 72, file=out)


def regret_for_choice(rec: dict, action_id: int):
    """Regret of a human `action_id` in `rec`. Returns (regret, kind, matched_best).
    * exact: objective regret (points lost vs optimal, mover-perspective, >=0);
             +inf if the action is somehow not scored.
    * midgame: Q-regret = best_Q - chosen_Q (in leaf-value units, >=0), or None
      if the chosen action was never visited by the labeling search."""
    a = int(action_id)
    if rec.get("exact"):
        cv = {int(k): v for k, v in rec["child_values"].items()}
        if a not in cv:
            return float("inf"), "exact", False
        vstar = rec["vstar"]
        reg = (vstar - cv[a]) if rec["to_move"] == 0 else (cv[a] - vstar)
        return max(0.0, float(reg)), "exact", a in set(rec["optimal_actions"])
    # midgame: use the labeled child Q
    label = rec.get("label") or {}
    q = {int(k): v for k, v in (label.get("child_q") or {}).items()}
    if not q:
        return None, "unlabeled", a == rec.get("best_move")
    if a not in q:
        return None, "midgame_unvisited", a == rec.get("best_move")
    best_q = q[rec["best_move"]] if rec["best_move"] in q else max(q.values())
    return max(0.0, float(best_q - q[a])), "midgame_q", a == rec.get("best_move")


def score_choices(suite_path: Path, choices: dict) -> dict:
    """`choices` = {position_id: chosen_action_id}. Emits per-stratum regret."""
    from statistics import mean
    per_stratum: dict[str, list] = {}
    rows = []
    for line in Path(suite_path).read_text().splitlines():
        if not line.strip():
            continue
        rec = json.loads(line)
        if rec["id"] not in choices:
            continue
        reg, kind, matched = regret_for_choice(rec, choices[rec["id"]])
        rows.append({"id": rec["id"], "stratum": rec["stratum"], "kind": kind,
                     "regret": reg, "matched_best": matched,
                     "chosen": int(choices[rec["id"]]), "best": rec.get("best_move")})
        per_stratum.setdefault(rec["stratum"], []).append((reg, matched))
    summary = {}
    for strat, vals in per_stratum.items():
        finite = [r for r, _ in vals if r is not None and r != float("inf")]
        summary[strat] = {
            "n": len(vals),
            "mean_regret": (round(mean(finite), 3) if finite else None),
            "match_rate": round(sum(1 for _, m in vals if m) / len(vals), 3),
        }
    return {"rows": rows, "per_stratum": summary}


# --------------------------------------------------------------------------- #
# self-test  (RUNS end-to-end: build 3 exact + 2 midgame, render, score fake human)
# --------------------------------------------------------------------------- #
def self_test() -> int:
    print("=== build_suite self-test ===")
    print("[1] exact-from-cache (K=2, no solver) ...")
    exact = build_exact_from_cache(limit=3)
    assert len(exact) == 3, f"expected 3 exact recs, got {len(exact)}"
    for r in exact:
        assert r["exact"] and r["child_values"] and r["optimal_actions"]
        assert str(r["best_move"]) in r["child_values"]
    print(f"    built {len(exact)} exact K=2 records "
          f"(ids: {[r['id'] for r in exact]})")

    print("[2] midgame search-labeled (low sims=80 smoke, NOT h6400) ...")
    seeds = [r["provenance"]["deck_seed"] for r in exact]
    mid = build_midgame_records(seeds[:2], ply=70, sims=80, agent_name="heur@80(smoke)")
    assert len(mid) >= 1, "expected >=1 midgame rec"
    for r in mid:
        assert not r["exact"] and r["label"]["child_q"]
        assert str(r["best_move"]) in r["label"]["child_q"]
    print(f"    built {len(mid)} midgame records "
          f"(strata: {[r['stratum'] for r in mid]})")

    suite = exact + mid
    tmp = Path(C.REPO_ROOT / "measurement/human_anchor/_selftest_suite.jsonl")
    tmp.write_text("".join(json.dumps(r) + "\n" for r in suite))
    print(f"[3] wrote {len(suite)} records -> {tmp}")

    print("[4] render (first record shown):")
    _g, b0 = C.reconstruct(suite[0]["provenance"])
    print("\n".join("    " + ln for ln in C.render_position(suite[0], b0).splitlines()[:14]))

    print("[5] score a FAKE human (exact: pick a deliberately suboptimal legal "
          "move; midgame: pick the labeled best):")
    choices = {}
    for r in exact:
        opt = set(r["optimal_actions"])
        bad = next((a for a in r["legal_moves"] if a not in opt), r["best_move"])
        choices[r["id"]] = bad
    for r in mid:
        choices[r["id"]] = r["best_move"]  # perfect play -> 0 regret
    result = score_choices(tmp, choices)
    print("    per-stratum:")
    for strat, s in result["per_stratum"].items():
        print(f"      {strat:<16} n={s['n']}  mean_regret={s['mean_regret']}  "
              f"match_rate={s['match_rate']}")
    # assertions: a deliberately-suboptimal exact choice must show >0 regret OR be
    # a forced tie (all legal optimal); the perfect midgame choice must match.
    any_exact_regret = any(
        row["regret"] and row["regret"] > 0 for row in result["rows"]
        if row["kind"] == "exact")
    forced = all(len(r["optimal_actions"]) == len(r["legal_moves"]) for r in exact)
    assert any_exact_regret or forced, "scorer failed to detect suboptimal exact move"
    assert all(row["matched_best"] for row in result["rows"]
               if row["kind"].startswith("midgame")), "midgame best-match failed"
    tmp.unlink(missing_ok=True)
    print("=== self-test PASSED ===")
    return 0


# --------------------------------------------------------------------------- #
def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="build_suite")
    ap.add_argument("--self-test", action="store_true", help="RUN end-to-end mini pipeline")
    ap.add_argument("--from-cache", action="store_true",
                    help="build exact K=2 records from the on-disk solver cache (cheap)")
    ap.add_argument("--generate", action="store_true",
                    help="HEAVY: solve K>=3 endgames + label midgames (needs boxes)")
    ap.add_argument("--run-solver", action="store_true",
                    help="required confirmation for --generate solver calls")
    ap.add_argument("--render", action="store_true")
    ap.add_argument("--score", action="store_true")
    ap.add_argument("--suite", type=Path)
    ap.add_argument("--choices", type=Path, help="JSON {position_id: action_id}")
    ap.add_argument("--out", type=Path)
    ap.add_argument("--ks", type=int, nargs="+", default=[3, 4])
    ap.add_argument("--limit", type=int, default=None)
    ap.add_argument("--midgame-sims", type=int, default=6400)
    ap.add_argument("--midgame-plies", type=int, nargs="+", default=[60, 80, 100])
    args = ap.parse_args(argv)

    if args.self_test:
        return self_test()

    if args.from_cache:
        recs = build_exact_from_cache(limit=args.limit)
        out = args.out or (C.REPO_ROOT / "measurement/human_anchor/suite_exact_k2.jsonl")
        Path(out).write_text("".join(json.dumps(r) + "\n" for r in recs))
        print(f"wrote {len(recs)} exact K=2 records -> {out}")
        return 0

    if args.generate:
        if not args.run_solver:
            print("REFUSING: --generate is CPU-heavy (exact solves + h6400 search) "
                  "and NEEDS BOXES. Re-run with --run-solver once boxes are free.\n"
                  "  (K=2 exact records are free via --from-cache; use that for now.)",
                  file=sys.stderr)
            return 2
        out = args.out or (C.REPO_ROOT / "measurement/human_anchor/suite.jsonl")
        n = 0
        for line in generate_exact_records(ks=tuple(args.ks), limit=args.limit, out_path=out):  # type: ignore
            n += 1
        print(f"generate: appended exact K={args.ks} records -> {out}")
        return 0

    if args.render:
        assert args.suite, "--render needs --suite"
        render_suite(args.suite)
        return 0

    if args.score:
        assert args.suite and args.choices, "--score needs --suite and --choices"
        choices = {k: int(v) for k, v in json.loads(Path(args.choices).read_text()).items()}
        result = score_choices(args.suite, choices)
        print(json.dumps(result["per_stratum"], indent=2))
        return 0

    ap.print_help()
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
