"""Side-by-side T1 (network-vs-random) comparison between two trained nets.

Reads per-game JSON checkpoints from two `data/tournament/<subdir>/` dirs
that were generated by `eval_warmstart_smoke.py --results-subdir <name>` at
the same `--seed-start` and `--n`. Each side's per-game files have the
form `seed{seed:06d}_p{net_player}.json`.

Output: a markdown report at `data/phase3_diagnostic/<output>.md` with:

  - aggregate win counts and avg score diff for each side
  - delta (B − A) on wins and avg diff
  - per-seed comparison: who won, score margins, agreement count

Optionally appends a training-metrics block from a captured trainer log
(--train-log) — last-epoch train/val pol CE + val MSE for each side.

Usage:
  python scripts/compare_t1_head_to_head.py \\
    --label-a v2 --subdir-a eval_phase3_t1_v2 \\
    --label-b v3 --subdir-b eval_phase3_t1_v3 \\
    --train-log-b /tmp/train_v3.log \\
    --output v3_vs_v2_t1.md
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TOURNAMENT_ROOT = REPO_ROOT / "data" / "tournament"
OUT_DIR = REPO_ROOT / "data" / "phase3_diagnostic"


def _load_subdir(subdir: str) -> dict[tuple[int, int], dict]:
    """Map (seed, net_player) → game result dict."""
    root = TOURNAMENT_ROOT / subdir
    if not root.exists():
        print(f"missing: {root}", file=sys.stderr)
        return {}
    out: dict[tuple[int, int], dict] = {}
    for f in sorted(root.glob("seed*.json")):
        try:
            with f.open() as fh:
                r = json.load(fh)
        except Exception as exc:
            print(f"  load fail {f.name}: {exc}", file=sys.stderr)
            continue
        out[(r["seed"], r["net_player"])] = r
    return out


def _aggregate(games: dict[tuple[int, int], dict]) -> dict:
    n = len(games)
    if n == 0:
        return {"n": 0, "wins": 0, "draws": 0, "losses": 0,
                "win_rate": 0.0, "avg_diff": 0.0, "avg_moves": 0.0}
    wins = sum(1 for g in games.values() if g["won"])
    draws = sum(1 for g in games.values() if g["drew"])
    losses = n - wins - draws
    avg_diff = sum(g["diff"] for g in games.values()) / n
    avg_moves = sum(g["moves"] for g in games.values()) / n
    return {
        "n": n, "wins": wins, "draws": draws, "losses": losses,
        "win_rate": wins / n, "avg_diff": avg_diff, "avg_moves": avg_moves,
    }


_TRAIN_EPOCH_RE = re.compile(
    r"epoch\s+(\d+)/\d+.*?train.*?loss\s*=\s*([\d.]+).*?pol\s*=\s*([\d.]+).*?val\s*=\s*([\d.]+)?",
    re.IGNORECASE,
)


def _parse_train_log(path: Path) -> str:
    """Best-effort extraction of per-epoch metrics from a trainer log.
    Returns a markdown snippet (or 'no parseable metrics' message). The
    trainer's exact format may vary; this is intentionally lenient."""
    if not path.exists():
        return f"_(train log not found at {path})_"
    text = path.read_text()
    # Capture lines that look like epoch progress.
    rows = []
    for line in text.splitlines():
        # Trainer format: "  epoch  N/M (Xs, K batches)  train pol/val=A/B  val pol/val=C/D"
        # — match anything with "epoch" and a slash-separated metric pair.
        low = line.lower()
        if "epoch" in low and "pol/val" in low:
            rows.append(line.strip())
    if not rows:
        return "_(no parseable per-epoch lines in trainer log)_"
    snippet = "```\n" + "\n".join(rows[-25:]) + "\n```\n"
    return snippet


def _decision_verdict(a_rate: float, b_rate: float) -> str:
    delta_pp = (b_rate - a_rate) * 100
    if delta_pp >= 5 and b_rate >= 0.90:
        return (f"**Decision rule: PROCEED to T2 on B.** B beats A by "
                f"{delta_pp:+.1f}pp AND clears the 90% bar (B={b_rate:.0%}). "
                f"Per the user's directive: do **not** autonomously run T2; "
                f"report and stop.")
    if abs(delta_pp) <= 3:
        return (f"**Decision rule: WASH.** B vs A within ±3pp "
                f"(delta={delta_pp:+.1f}pp). Relabeling did not move the "
                f"needle. Report and stop; next path is the user's call.")
    if delta_pp <= -5:
        return (f"**Decision rule: B WORSE.** B underperforms A by "
                f"{delta_pp:+.1f}pp. The noise concern was real and "
                f"snapshot labels were preferable. Report and stop.")
    # Mid-ground (between ±3pp and ±5pp, or A>=90 but b<a by 4pp etc.):
    return (f"**Decision rule: AMBIGUOUS.** delta={delta_pp:+.1f}pp, "
            f"B={b_rate:.0%}. Falls outside the three crisp branches; "
            f"flagging for user review. Report and stop.")


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="compare_t1_head_to_head")
    p.add_argument("--label-a", default="A")
    p.add_argument("--subdir-a", required=True,
                   help="data/tournament/<subdir-a>/")
    p.add_argument("--label-b", default="B")
    p.add_argument("--subdir-b", required=True,
                   help="data/tournament/<subdir-b>/")
    p.add_argument("--train-log-a", type=Path, default=None)
    p.add_argument("--train-log-b", type=Path, default=None)
    p.add_argument("--output", default="v3_vs_v2_t1.md",
                   help="filename under data/phase3_diagnostic/")
    args = p.parse_args(argv)

    games_a = _load_subdir(args.subdir_a)
    games_b = _load_subdir(args.subdir_b)
    if not games_a:
        print(f"no games for {args.label_a}", file=sys.stderr)
        return 1
    if not games_b:
        print(f"no games for {args.label_b}", file=sys.stderr)
        return 1

    common_keys = sorted(set(games_a.keys()) & set(games_b.keys()))
    only_a = sorted(set(games_a.keys()) - set(games_b.keys()))
    only_b = sorted(set(games_b.keys()) - set(games_a.keys()))

    agg_a = _aggregate(games_a)
    agg_b = _aggregate(games_b)
    # Restrict aggregate to the intersection for the head-to-head numbers.
    agg_a_intersect = _aggregate({k: games_a[k] for k in common_keys})
    agg_b_intersect = _aggregate({k: games_b[k] for k in common_keys})

    # Per-seed comparison.
    rows = []
    a_won_b_lost = 0
    a_lost_b_won = 0
    both_won = 0
    both_lost = 0
    for k in common_keys:
        ga = games_a[k]
        gb = games_b[k]
        if ga["won"] and gb["won"]:
            both_won += 1
        elif (not ga["won"]) and (not gb["won"]):
            both_lost += 1
        elif ga["won"] and (not gb["won"]):
            a_won_b_lost += 1
        elif (not ga["won"]) and gb["won"]:
            a_lost_b_won += 1
        rows.append((k, ga, gb))

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUT_DIR / args.output
    with out_path.open("w") as fh:
        fh.write(f"# T1 head-to-head: {args.label_a} vs {args.label_b}\n\n")
        fh.write(
            f"Comparing two trained nets on identical seeds (network-vs-random T1).\n"
            f"Both nets play {agg_a['n']} games each at the same seeds with the "
            f"same alternating net_player schedule. Caching means re-runs are "
            f"deterministic per (seed, net_player).\n\n"
        )

        fh.write("## Aggregate (intersection of seeds)\n\n")
        fh.write(f"| Metric | {args.label_a} | {args.label_b} | Δ ({args.label_b} − {args.label_a}) |\n")
        fh.write("|---|---|---|---|\n")
        fh.write(f"| Games | {agg_a_intersect['n']} | {agg_b_intersect['n']} | — |\n")
        fh.write(
            f"| Wins | {agg_a_intersect['wins']} ({agg_a_intersect['win_rate']:.0%}) | "
            f"{agg_b_intersect['wins']} ({agg_b_intersect['win_rate']:.0%}) | "
            f"{agg_b_intersect['wins'] - agg_a_intersect['wins']:+d} "
            f"({(agg_b_intersect['win_rate']-agg_a_intersect['win_rate'])*100:+.1f}pp) |\n"
        )
        fh.write(
            f"| Draws | {agg_a_intersect['draws']} | {agg_b_intersect['draws']} | "
            f"{agg_b_intersect['draws'] - agg_a_intersect['draws']:+d} |\n"
        )
        fh.write(
            f"| Losses | {agg_a_intersect['losses']} | {agg_b_intersect['losses']} | "
            f"{agg_b_intersect['losses'] - agg_a_intersect['losses']:+d} |\n"
        )
        fh.write(
            f"| Avg score diff (net − rand) | {agg_a_intersect['avg_diff']:+.1f} | "
            f"{agg_b_intersect['avg_diff']:+.1f} | "
            f"{agg_b_intersect['avg_diff'] - agg_a_intersect['avg_diff']:+.1f} |\n"
        )
        fh.write(
            f"| Avg moves/game | {agg_a_intersect['avg_moves']:.0f} | "
            f"{agg_b_intersect['avg_moves']:.0f} | — |\n\n"
        )

        if only_a or only_b:
            fh.write(f"_Note: {len(only_a)} seeds in {args.label_a}-only, "
                     f"{len(only_b)} in {args.label_b}-only. Aggregate uses "
                     f"the {len(common_keys)} intersection seeds._\n\n")

        fh.write("## Per-seed agreement\n\n")
        n_int = len(common_keys)
        fh.write(f"| Outcome | Count | % |\n")
        fh.write("|---|---|---|\n")
        fh.write(f"| Both won | {both_won} | {both_won/max(n_int,1):.0%} |\n")
        fh.write(f"| {args.label_a} won, {args.label_b} lost | {a_won_b_lost} | {a_won_b_lost/max(n_int,1):.0%} |\n")
        fh.write(f"| {args.label_a} lost, {args.label_b} won | {a_lost_b_won} | {a_lost_b_won/max(n_int,1):.0%} |\n")
        fh.write(f"| Both lost | {both_lost} | {both_lost/max(n_int,1):.0%} |\n\n")

        fh.write("## Verdict\n\n")
        fh.write(_decision_verdict(agg_a_intersect['win_rate'], agg_b_intersect['win_rate']))
        fh.write("\n\n")

        if args.train_log_a is not None or args.train_log_b is not None:
            fh.write("## Training metrics\n\n")
            if args.train_log_a is not None:
                fh.write(f"### {args.label_a}\n\n")
                fh.write(_parse_train_log(args.train_log_a))
                fh.write("\n")
            if args.train_log_b is not None:
                fh.write(f"### {args.label_b}\n\n")
                fh.write(_parse_train_log(args.train_log_b))
                fh.write("\n")

        # Per-seed table (full).
        fh.write("## Per-seed detail\n\n")
        fh.write(f"| Seed | NetP | {args.label_a} won | {args.label_a} diff | {args.label_b} won | {args.label_b} diff | agree? |\n")
        fh.write("|---|---|---|---|---|---|---|\n")
        for k, ga, gb in rows:
            seed, np_ = k
            agree = "yes" if ga["won"] == gb["won"] else "DIFF"
            fh.write(
                f"| {seed} | P{np_} | {'W' if ga['won'] else ('D' if ga['drew'] else 'L')} | "
                f"{ga['diff']:+d} | {'W' if gb['won'] else ('D' if gb['drew'] else 'L')} | "
                f"{gb['diff']:+d} | {agree} |\n"
            )

    print(f"Wrote {out_path}")
    print()
    print(f"{args.label_a}: {agg_a_intersect['wins']}/{agg_a_intersect['n']} "
          f"({agg_a_intersect['win_rate']:.0%}), avg diff {agg_a_intersect['avg_diff']:+.1f}")
    print(f"{args.label_b}: {agg_b_intersect['wins']}/{agg_b_intersect['n']} "
          f"({agg_b_intersect['win_rate']:.0%}), avg diff {agg_b_intersect['avg_diff']:+.1f}")
    print(f"Δ: {(agg_b_intersect['win_rate']-agg_a_intersect['win_rate'])*100:+.1f}pp")
    return 0


if __name__ == "__main__":
    sys.exit(main())
