//! Double-precision `exp` and `tanh` ported to Rust so the search does not
//! depend on the platform libm.
//!
//! **These are HYPOTHESES.** The port is faithful to a named upstream; whether a
//! given platform's `np.exp` / `math.tanh` actually *is* that upstream is what
//! `scripts/rustport/harness_transcendental.py` measures. Do not adjust the code
//! to chase a mismatch — record the mismatch.
//!
//! Provenance
//! ----------
//! * [`exp64`] — ARM optimized-routines `math/exp.c` (`exp_inline(x, 0, 0)`),
//!   `EXP_TABLE_BITS = 7`, `EXP_POLY_ORDER = 5`, `TOINT_INTRINSICS = 0`,
//!   `EXP_USE_TOINT_NARROW = 0`. This is the implementation glibc adopted for
//!   `exp()` in 2.27 (`sysdeps/ieee754/dbl-64/e_exp.c`) and the common ancestor
//!   of what bionic ships. Data table: [`super::exp_data`], generated by
//!   `scripts/rustport/gen_exp_table.py`.
//!   <https://github.com/ARM-software/optimized-routines>
//!   SPDX: MIT OR Apache-2.0 WITH LLVM-exception, Copyright (c) 2018-2019 Arm Limited.
//! * [`tanh64`] / [`expm1_64`] — fdlibm / FreeBSD msun `s_tanh.c` and `s_expm1.c`.
//!   Copyright (C) 1993 by Sun Microsystems, Inc. glibc's
//!   `sysdeps/ieee754/dbl-64/s_tanh.c` is this same code, as is bionic's (via
//!   FreeBSD msun).
//!
//! FMA contraction
//! ---------------
//! glibc on x86-64 ships an ifunc-selected `__exp_fma` built from the *same*
//! source with `-mfma -mavx2`, which lets the compiler contract
//! `x + kd*NegLn2hiN + kd*NegLn2loN` and the polynomial into FMAs — a different
//! function of the same input. aarch64 always has FMA available. Rust never
//! contracts implicitly, so [`exp64`] is the *non-contracted* build and
//! [`exp64_fma`] is the contracted one. The harness reports which (if either)
//! reproduces the local `np.exp`; that is the G0 dispatch finding.

use super::exp_data as d;

#[inline(always)]
fn as_u64(x: f64) -> u64 {
    x.to_bits()
}
#[inline(always)]
fn as_f64(x: u64) -> f64 {
    f64::from_bits(x)
}
/// Top 12 bits of a double (sign and exponent bits).
#[inline(always)]
fn top12(x: f64) -> u32 {
    (as_u64(x) >> 52) as u32
}

/// `specialcase` from ARM `exp.c` — the overflow/underflow-adjacent tail.
fn exp_specialcase(tmp: f64, mut sbits: u64, ki: u64) -> f64 {
    if (ki & 0x8000_0000) == 0 {
        // k > 0, the exponent of scale might have overflowed by <= 460.
        sbits = sbits.wrapping_sub(1009u64 << 52);
        let scale = as_f64(sbits);
        return P1009 * (scale + scale * tmp);
    }
    // k < 0, need special care in the subnormal range.
    sbits = sbits.wrapping_add(1022u64 << 52);
    let scale = as_f64(sbits);
    let mut y = scale + scale * tmp;
    if y < 1.0 {
        // Round y to the right precision before scaling it into the subnormal
        // range to avoid double rounding.
        let mut lo = scale - y + scale * tmp;
        let hi = 1.0 + y;
        lo = 1.0 - hi + y + lo;
        y = (hi + lo) - 1.0;
        // Avoid -0.0 with downward rounding.
        if y == 0.0 {
            y = 0.0;
        }
    }
    PM1022 * y
}

const P1009: f64 = f64::from_bits(0x7F00000000000000); // 0x1p1009
const PM1022: f64 = f64::from_bits(0x0010000000000000); // 0x1p-1022
const PM54: f64 = f64::from_bits(0x3C90000000000000); // 0x1p-54

/// `exp(x)` — ARM optimized-routines, **without** FMA contraction.
pub fn exp64(x: f64) -> f64 {
    exp_inline::<false>(x)
}

/// `exp(x)` — the same algorithm with the multiply-adds contracted into FMAs,
/// modelling glibc's `-mfma` x86-64 ifunc variant and aarch64 codegen.
pub fn exp64_fma(x: f64) -> f64 {
    exp_inline::<true>(x)
}

#[inline]
fn exp_inline<const FMA: bool>(x: f64) -> f64 {
    let mut abstop = top12(x) & 0x7ff;
    if abstop.wrapping_sub(top12(PM54)) >= top12(512.0).wrapping_sub(top12(PM54)) {
        if abstop.wrapping_sub(top12(PM54)) >= 0x8000_0000 {
            // Avoid spurious underflow for tiny x. (0 is a common input.)
            return 1.0 + x;
        }
        if abstop >= top12(1024.0) {
            if as_u64(x) == as_u64(f64::NEG_INFINITY) {
                return 0.0;
            }
            if abstop >= top12(f64::INFINITY) {
                return 1.0 + x;
            }
            if as_u64(x) >> 63 != 0 {
                return 0.0; // __math_uflow(0)
            }
            return f64::INFINITY; // __math_oflow(0)
        }
        // Large x is special cased below.
        abstop = 0;
    }

    // exp(x) = 2^(k/N) * exp(r), with exp(r) in [2^(-1/2N), 2^(1/2N)].
    let z = d::INV_LN2_N * x;
    // !TOINT_INTRINSICS && !EXP_USE_TOINT_NARROW
    let kd0 = z + d::SHIFT;
    let ki = as_u64(kd0);
    let kd = kd0 - d::SHIFT;

    let r = if FMA {
        // glibc's -mfma build contracts these two multiply-adds.
        kd.mul_add(d::NEG_LN2_LO_N, kd.mul_add(d::NEG_LN2_HI_N, x))
    } else {
        x + kd * d::NEG_LN2_HI_N + kd * d::NEG_LN2_LO_N
    };

    // 2^(k/N) ~= scale * (1 + tail).
    let idx = (2 * (ki % d::N)) as usize;
    let top = ki << (52 - d::EXP_TABLE_BITS);
    let tail = as_f64(d::TAB[idx]);
    // Only a valid scale when -1023*N < k < 1024*N.
    let sbits = d::TAB[idx + 1].wrapping_add(top);

    let r2 = r * r;
    // EXP_POLY_ORDER == 5:
    //   tmp = tail + r + r2 * (C2 + r * C3) + r2 * r2 * (C4 + r * C5);
    let tmp = if FMA {
        let a = r.mul_add(d::C3, d::C2);
        let b = r.mul_add(d::C5, d::C4);
        (r2 * r2).mul_add(b, r2.mul_add(a, tail + r))
    } else {
        tail + r + r2 * (d::C2 + r * d::C3) + r2 * r2 * (d::C4 + r * d::C5)
    };

    if abstop == 0 {
        return exp_specialcase(tmp, sbits, ki);
    }
    let scale = as_f64(sbits);
    if FMA {
        scale.mul_add(tmp, scale)
    } else {
        scale + scale * tmp
    }
}

// --------------------------------------------------------------------------
// fdlibm expm1 / tanh
// --------------------------------------------------------------------------

const ONE: f64 = 1.0;
const TINY: f64 = 1.0e-300;
const HUGE: f64 = 1.0e300;
const O_THRESHOLD: f64 = 7.097_827_128_933_839_7e2; // 0x40862E42, 0xFEFA39EF
const LN2_HI: f64 = 6.931_471_803_691_238_2e-1; // 0x3fe62e42, 0xfee00000
const LN2_LO: f64 = 1.908_214_929_270_587_7e-10; // 0x3dea39ef, 0x35793c76
const INVLN2: f64 = 1.442_695_040_888_963_4; // 0x3ff71547, 0x652b82fe
// Scaled Q's: Qn_here = 2**n * Qn_above, for R(2*z) where z = hxs = x*x/2
const Q1: f64 = -3.333_333_333_333_313_2e-2; // BFA11111 111110F4
const Q2: f64 = 1.587_301_587_254_814_6e-3; // 3F5A01A0 19FE5585
const Q3: f64 = -7.936_507_578_674_879_4e-5; // BF14CE19 9EAADBB7
const Q4: f64 = 4.008_217_827_329_362_4e-6; // 3ED0CFCA 86E65239
const Q5: f64 = -2.010_992_181_836_243_7e-7; // BE8AFDB7 6E09C32D

#[inline(always)]
fn high_word(x: f64) -> u32 {
    (as_u64(x) >> 32) as u32
}
#[inline(always)]
fn low_word(x: f64) -> u32 {
    as_u64(x) as u32
}
#[inline(always)]
fn set_high_word(x: f64, hi: u32) -> f64 {
    as_f64(((hi as u64) << 32) | (low_word(x) as u64))
}
#[inline(always)]
fn insert_words(hi: u32, lo: u32) -> f64 {
    as_f64(((hi as u64) << 32) | (lo as u64))
}

/// `expm1(x)` — fdlibm / FreeBSD msun `s_expm1.c`.
pub fn expm1_64(mut x: f64) -> f64 {
    let mut hx = high_word(x);
    let xsb = hx & 0x8000_0000; // sign bit of x
    hx &= 0x7fff_ffff; // high word of |x|

    // filter out huge and non-finite argument
    if hx >= 0x4043_687A {
        // |x| >= 56*ln2
        if hx >= 0x4086_2E42 {
            // |x| >= 709.78...
            if hx >= 0x7ff0_0000 {
                if ((hx & 0xf_ffff) | low_word(x)) != 0 {
                    return x + x; // NaN
                }
                return if xsb == 0 { x } else { -1.0 }; // exp(+-inf) = {inf, -1}
            }
            if x > O_THRESHOLD {
                return HUGE * HUGE; // overflow
            }
        }
        if xsb != 0 {
            // x < -56*ln2, return -1.0 with inexact
            if x + TINY < 0.0 {
                return TINY - ONE;
            }
        }
    }

    let k: i32;
    let mut c = 0.0f64;
    // argument reduction
    if hx > 0x3fd6_2e42 {
        // |x| > 0.5 ln2
        let hi: f64;
        let lo: f64;
        if hx < 0x3FF0_A2B2 {
            // and |x| < 1.5 ln2
            if xsb == 0 {
                hi = x - LN2_HI;
                lo = LN2_LO;
                k = 1;
            } else {
                hi = x + LN2_HI;
                lo = -LN2_LO;
                k = -1;
            }
        } else {
            k = (INVLN2 * x + if xsb == 0 { 0.5 } else { -0.5 }) as i32;
            let t = k as f64;
            hi = x - t * LN2_HI; // t*ln2_hi is exact here
            lo = t * LN2_LO;
        }
        x = hi - lo;
        c = (hi - x) - lo;
    } else if hx < 0x3c90_0000 {
        // |x| < 2**-54, return x
        let t = HUGE + x;
        return x - (t - (HUGE + x));
    } else {
        k = 0;
    }

    // x is now in primary range
    let hfx = 0.5 * x;
    let hxs = x * hfx;
    let r1 = ONE + hxs * (Q1 + hxs * (Q2 + hxs * (Q3 + hxs * (Q4 + hxs * Q5))));
    let t = 3.0 - r1 * hfx;
    let mut e = hxs * ((r1 - t) / (6.0 - x * t));
    if k == 0 {
        return x - (x * e - hxs); // c is 0
    }
    let twopk = insert_words(((0x3ff + k) as u32) << 20, 0); // 2^k
    e = x * (e - c) - c;
    e -= hxs;
    if k == -1 {
        return 0.5 * (x - e) - 0.5;
    }
    if k == 1 {
        if x < -0.25 {
            return -2.0 * (e - (x + 0.5));
        }
        return ONE + 2.0 * (x - e);
    }
    let y: f64;
    if k <= -2 || k > 56 {
        // suffice to return exp(x) - 1
        let mut yy = ONE - (e - x);
        if k == 1024 {
            yy = yy * 2.0 * f64::from_bits(0x7FE0000000000000); // 0x1p1023
        } else {
            yy *= twopk;
        }
        return yy - ONE;
    }
    let mut t = ONE;
    if k < 20 {
        t = set_high_word(t, 0x3ff0_0000 - (0x20_0000u32 >> k)); // t = 1 - 2^-k
        y = (t - (e - x)) * twopk;
    } else {
        t = set_high_word(t, ((0x3ff - k) as u32) << 20); // t = 2^-k
        let mut yy = x - (e + t);
        yy += ONE;
        y = yy * twopk;
    }
    y
}

/// `tanh(x)` — fdlibm / FreeBSD msun `s_tanh.c`.
pub fn tanh64(x: f64) -> f64 {
    let jx = high_word(x) as i32;
    let ix = jx & 0x7fff_ffff;

    // x is INF or NaN
    if ix >= 0x7ff0_0000 {
        return if jx >= 0 { ONE / x + ONE } else { ONE / x - ONE };
    }

    let z: f64;
    if ix < 0x4036_0000 {
        // |x| < 22
        if ix < 0x3e30_0000 {
            // |x| < 2**-28
            if HUGE + x > ONE {
                return x; // tanh(tiny) = tiny with inexact
            }
        }
        if ix >= 0x3ff0_0000 {
            // |x| >= 1
            let t = expm1_64(2.0 * x.abs());
            z = ONE - 2.0 / (t + 2.0);
        } else {
            let t = expm1_64(-2.0 * x.abs());
            z = -t / (t + 2.0);
        }
    } else {
        // |x| >= 22, return +-1
        z = ONE - TINY; // raise inexact flag
    }
    if jx >= 0 {
        z
    } else {
        -z
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Distance in ULPs between two finite doubles.
    fn ulp_diff(a: f64, b: f64) -> u64 {
        if a == b {
            return 0;
        }
        let ai = a.to_bits() as i64;
        let bi = b.to_bits() as i64;
        // map to a monotone ordering
        let m = |v: i64| if v < 0 { i64::MIN - v } else { v };
        (m(ai) - m(bi)).unsigned_abs()
    }

    #[test]
    fn exp_exact_special_points() {
        assert_eq!(exp64(0.0).to_bits(), 1.0f64.to_bits());
        assert_eq!(exp64(-0.0).to_bits(), 1.0f64.to_bits());
        assert_eq!(exp64(f64::NEG_INFINITY), 0.0);
        assert_eq!(exp64(f64::INFINITY), f64::INFINITY);
        assert!(exp64(f64::NAN).is_nan());
        assert_eq!(exp64(1000.0), f64::INFINITY);
        assert_eq!(exp64(-1000.0), 0.0);
    }

    #[test]
    fn exp_agrees_with_std_within_1_ulp() {
        // std's f64::exp calls the platform libm. This is a sanity band, not a
        // parity claim -- the harness makes the parity claim.
        let mut worst = 0u64;
        let mut x = -100.0f64;
        while x <= 20.0 {
            let a = exp64(x);
            let b = x.exp();
            worst = worst.max(ulp_diff(a, b));
            x += 0.0007771;
        }
        assert!(worst <= 1, "exp64 vs std worst ulp = {worst}");
    }

    #[test]
    fn exp_fma_variant_is_close_to_scalar() {
        let mut worst = 0u64;
        let mut x = -50.0f64;
        while x <= 10.0 {
            worst = worst.max(ulp_diff(exp64(x), exp64_fma(x)));
            x += 0.0013;
        }
        assert!(worst <= 1, "exp64 vs exp64_fma worst ulp = {worst}");
    }

    #[test]
    fn exp_subnormal_and_overflow_edges() {
        // Just below/above the boundaries where specialcase() engages.
        for &x in &[-745.0f64, -744.5, -708.0, -709.9, 709.0, 709.78, 709.79] {
            let a = exp64(x);
            let b = x.exp();
            assert!(ulp_diff(a, b) <= 1 || (a == b), "x={x} a={a:e} b={b:e}");
        }
    }

    #[test]
    fn tanh_exact_special_points() {
        assert_eq!(tanh64(0.0).to_bits(), 0.0f64.to_bits());
        assert_eq!(tanh64(-0.0).to_bits(), (-0.0f64).to_bits());
        assert_eq!(tanh64(f64::INFINITY), 1.0);
        assert_eq!(tanh64(f64::NEG_INFINITY), -1.0);
        assert!(tanh64(f64::NAN).is_nan());
        assert_eq!(tanh64(30.0), 1.0);
        assert_eq!(tanh64(-30.0), -1.0);
    }

    #[test]
    fn tanh_is_odd() {
        let mut x = 0.0f64;
        while x < 25.0 {
            assert_eq!(tanh64(-x).to_bits(), (-tanh64(x)).to_bits(), "x={x}");
            x += 0.00317;
        }
    }

    /// **Finding (2026-07-31, glibc 2.39 / x86-64):** the fdlibm `tanh` port is
    /// NOT bit-identical to the platform `tanh` — worst observed disagreement is
    /// 3 ulp over [-20, 20]. `expm1` agrees to <= 1 ulp, so the divergence is in
    /// glibc's own `tanh` wrapper, not in the shared kernel. This is exactly the
    /// hypothesis `harness_transcendental.py` exists to price; the band here is a
    /// regression guard on the PORT, not a parity claim.
    #[test]
    fn tanh_band_vs_platform_libm() {
        let mut worst = 0u64;
        let mut worst_x = 0.0f64;
        let mut x = -20.0f64;
        while x <= 20.0 {
            let d = ulp_diff(tanh64(x), x.tanh());
            if d > worst {
                worst = d;
                worst_x = x;
            }
            x += 0.000431;
        }
        assert!(
            worst <= 4,
            "tanh64 vs platform libm worst ulp = {worst} at x = {worst_x} \
             (expected <= 3 on glibc 2.39; a jump means the port regressed)"
        );
    }

    /// glibc 2.39's `expm1` agrees with the fdlibm port to <= 1 ulp but is not
    /// bit-identical either (x86-64 selects an FMA-contracted multiarch build).
    #[test]
    fn expm1_agrees_with_std_within_1_ulp() {
        let mut worst = 0u64;
        let mut x = -40.0f64;
        while x <= 40.0 {
            let a = expm1_64(x);
            let b = x.exp_m1();
            worst = worst.max(ulp_diff(a, b));
            x += 0.000917;
        }
        assert!(worst <= 1, "expm1_64 vs std worst ulp = {worst}");
    }

    #[test]
    fn tanh_tiny_returns_argument() {
        let t = 1e-30f64;
        assert_eq!(tanh64(t).to_bits(), t.to_bits());
    }
}
