//! Double-precision `exp` and `tanh` ported to Rust so the search does not
//! depend on the platform libm.
//!
//! **These are HYPOTHESES.** The port is faithful to a named upstream; whether a
//! given platform's `np.exp` / `math.tanh` actually *is* that upstream is what
//! `scripts/rustport/harness_transcendental.py` measures. Do not adjust the code
//! to chase a mismatch — record the mismatch.
//!
//! Provenance
//! ----------
//! * [`exp64`] — ARM optimized-routines `math/exp.c` (`exp_inline(x, 0, 0)`),
//!   `EXP_TABLE_BITS = 7`, `EXP_POLY_ORDER = 5`, `TOINT_INTRINSICS = 0`,
//!   `EXP_USE_TOINT_NARROW = 0`. This is the implementation glibc adopted for
//!   `exp()` in 2.27 (`sysdeps/ieee754/dbl-64/e_exp.c`) and the common ancestor
//!   of what bionic ships. Data table: [`super::exp_data`], generated by
//!   `scripts/rustport/gen_exp_table.py`.
//!   <https://github.com/ARM-software/optimized-routines>
//!   SPDX: MIT OR Apache-2.0 WITH LLVM-exception, Copyright (c) 2018-2019 Arm Limited.
//! * [`tanh64`] / [`expm1_64`] — fdlibm / FreeBSD msun `s_tanh.c` and `s_expm1.c`.
//!   Copyright (C) 1993 by Sun Microsystems, Inc. glibc's
//!   `sysdeps/ieee754/dbl-64/s_tanh.c` is this same code, as is bionic's (via
//!   FreeBSD msun).
//!
//! FMA contraction
//! ---------------
//! glibc on x86-64 ships an ifunc-selected `__exp_fma` built from the *same*
//! source with `-mfma -mavx2`, which lets the compiler contract
//! `x + kd*NegLn2hiN + kd*NegLn2loN` and the polynomial into FMAs — a different
//! function of the same input. aarch64 always has FMA available. Rust never
//! contracts implicitly, so [`exp64`] is the *non-contracted* build and
//! [`exp64_fma`] is the contracted one. The harness reports which (if either)
//! reproduces the local `np.exp`; that is the G0 dispatch finding.

use super::exp_data as d;

#[inline(always)]
fn as_u64(x: f64) -> u64 {
    x.to_bits()
}
#[inline(always)]
fn as_f64(x: u64) -> f64 {
    f64::from_bits(x)
}
/// Top 12 bits of a double (sign and exponent bits).
#[inline(always)]
fn top12(x: f64) -> u32 {
    (as_u64(x) >> 52) as u32
}

/// `specialcase` from ARM `exp.c` — the overflow/underflow-adjacent tail.
fn exp_specialcase(tmp: f64, mut sbits: u64, ki: u64) -> f64 {
    if (ki & 0x8000_0000) == 0 {
        // k > 0, the exponent of scale might have overflowed by <= 460.
        sbits = sbits.wrapping_sub(1009u64 << 52);
        let scale = as_f64(sbits);
        return P1009 * (scale + scale * tmp);
    }
    // k < 0, need special care in the subnormal range.
    sbits = sbits.wrapping_add(1022u64 << 52);
    let scale = as_f64(sbits);
    let mut y = scale + scale * tmp;
    if y < 1.0 {
        // Round y to the right precision before scaling it into the subnormal
        // range to avoid double rounding.
        let mut lo = scale - y + scale * tmp;
        let hi = 1.0 + y;
        lo = 1.0 - hi + y + lo;
        y = (hi + lo) - 1.0;
        // Avoid -0.0 with downward rounding.
        if y == 0.0 {
            y = 0.0;
        }
    }
    PM1022 * y
}

const P1009: f64 = f64::from_bits(0x7F00000000000000); // 0x1p1009
const PM1022: f64 = f64::from_bits(0x0010000000000000); // 0x1p-1022
const PM54: f64 = f64::from_bits(0x3C90000000000000); // 0x1p-54

/// `exp(x)` — ARM optimized-routines, **without** FMA contraction.
pub fn exp64(x: f64) -> f64 {
    exp_inline::<false>(x)
}

/// `exp(x)` — the same algorithm with the multiply-adds contracted into FMAs,
/// modelling glibc's `-mfma` x86-64 ifunc variant and aarch64 codegen.
pub fn exp64_fma(x: f64) -> f64 {
    exp_inline::<true>(x)
}

#[inline]
fn exp_inline<const FMA: bool>(x: f64) -> f64 {
    let mut abstop = top12(x) & 0x7ff;
    if abstop.wrapping_sub(top12(PM54)) >= top12(512.0).wrapping_sub(top12(PM54)) {
        if abstop.wrapping_sub(top12(PM54)) >= 0x8000_0000 {
            // Avoid spurious underflow for tiny x. (0 is a common input.)
            return 1.0 + x;
        }
        if abstop >= top12(1024.0) {
            if as_u64(x) == as_u64(f64::NEG_INFINITY) {
                return 0.0;
            }
            if abstop >= top12(f64::INFINITY) {
                return 1.0 + x;
            }
            if as_u64(x) >> 63 != 0 {
                return 0.0; // __math_uflow(0)
            }
            return f64::INFINITY; // __math_oflow(0)
        }
        // Large x is special cased below.
        abstop = 0;
    }

    // exp(x) = 2^(k/N) * exp(r), with exp(r) in [2^(-1/2N), 2^(1/2N)].
    let z = d::INV_LN2_N * x;
    // !TOINT_INTRINSICS && !EXP_USE_TOINT_NARROW
    let kd0 = z + d::SHIFT;
    let ki = as_u64(kd0);
    let kd = kd0 - d::SHIFT;

    let r = if FMA {
        // glibc's -mfma build contracts these two multiply-adds.
        kd.mul_add(d::NEG_LN2_LO_N, kd.mul_add(d::NEG_LN2_HI_N, x))
    } else {
        x + kd * d::NEG_LN2_HI_N + kd * d::NEG_LN2_LO_N
    };

    // 2^(k/N) ~= scale * (1 + tail).
    let idx = (2 * (ki % d::N)) as usize;
    let top = ki << (52 - d::EXP_TABLE_BITS);
    let tail = as_f64(d::TAB[idx]);
    // Only a valid scale when -1023*N < k < 1024*N.
    let sbits = d::TAB[idx + 1].wrapping_add(top);

    let r2 = r * r;
    // EXP_POLY_ORDER == 5:
    //   tmp = tail + r + r2 * (C2 + r * C3) + r2 * r2 * (C4 + r * C5);
    let tmp = if FMA {
        let a = r.mul_add(d::C3, d::C2);
        let b = r.mul_add(d::C5, d::C4);
        (r2 * r2).mul_add(b, r2.mul_add(a, tail + r))
    } else {
        tail + r + r2 * (d::C2 + r * d::C3) + r2 * r2 * (d::C4 + r * d::C5)
    };

    if abstop == 0 {
        return exp_specialcase(tmp, sbits, ki);
    }
    let scale = as_f64(sbits);
    if FMA {
        scale.mul_add(tmp, scale)
    } else {
        scale + scale * tmp
    }
}

// --------------------------------------------------------------------------
// fdlibm expm1 / tanh
// --------------------------------------------------------------------------

const ONE: f64 = 1.0;
const TINY: f64 = 1.0e-300;
const HUGE: f64 = 1.0e300;
const O_THRESHOLD: f64 = 7.097_827_128_933_839_7e2; // 0x40862E42, 0xFEFA39EF
const LN2_HI: f64 = 6.931_471_803_691_238_2e-1; // 0x3fe62e42, 0xfee00000
const LN2_LO: f64 = 1.908_214_929_270_587_7e-10; // 0x3dea39ef, 0x35793c76
const INVLN2: f64 = 1.442_695_040_888_963_4; // 0x3ff71547, 0x652b82fe
// Scaled Q's: Qn_here = 2**n * Qn_above, for R(2*z) where z = hxs = x*x/2
const Q1: f64 = -3.333_333_333_333_313_2e-2; // BFA11111 111110F4
const Q2: f64 = 1.587_301_587_254_814_6e-3; // 3F5A01A0 19FE5585
const Q3: f64 = -7.936_507_578_674_879_4e-5; // BF14CE19 9EAADBB7
const Q4: f64 = 4.008_217_827_329_362_4e-6; // 3ED0CFCA 86E65239
const Q5: f64 = -2.010_992_181_836_243_7e-7; // BE8AFDB7 6E09C32D

#[inline(always)]
fn high_word(x: f64) -> u32 {
    (as_u64(x) >> 32) as u32
}
#[inline(always)]
fn low_word(x: f64) -> u32 {
    as_u64(x) as u32
}
#[inline(always)]
fn set_high_word(x: f64, hi: u32) -> f64 {
    as_f64(((hi as u64) << 32) | (low_word(x) as u64))
}
#[inline(always)]
fn insert_words(hi: u32, lo: u32) -> f64 {
    as_f64(((hi as u64) << 32) | (lo as u64))
}

/// The four platform hypotheses for `expm1` / `tanh`.
///
/// Two independent axes, both discovered by reading the sources rather than
/// guessing:
///
/// * **polynomial form** — FreeBSD msun evaluates the `expm1` kernel in plain
///   Horner; **glibc uses a different (Estrin-like) grouping** carrying the
///   1997 "Modified by Naohiko Shimizu ... for performance improvement on
///   pipelined processors" note:
///   ```text
///   R1 = one + hxs*Q1;  h2 = hxs*hxs;
///   R2 = Q2 + hxs*Q3;   h4 = h2*h2;
///   R3 = Q4 + hxs*Q5;
///   r1 = R1 + h2*R2 + h4*R3;
///   ```
///   That is a different rounding sequence, not a refactor. bionic is msun-derived,
///   so ANDROID AND DESKTOP ARE EXPECTED TO DIFFER HERE.
/// * **FMA contraction** — glibc x86-64 ships `s_expm1-fma.c`, the same source
///   compiled with `-mfma`, so GCC's default `-ffp-contract=fast` fuses every
///   `a*b +/- c`. aarch64 has FMA unconditionally.
///
/// `glibc` also differs from msun in `tanh`'s tiny-argument branch (`|x| < 2^-55`
/// returning `x*(1+x)`, plus an explicit `+-0` early return, vs msun's
/// `|x| < 2^-28` returning `x`). Outside the leaf's range, modelled anyway.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LibmFlavor {
    /// FreeBSD msun / fdlibm, no contraction — the bionic (Android) hypothesis.
    Msun,
    /// FreeBSD msun / fdlibm with FMA contraction.
    MsunFma,
    /// glibc's Shimizu-grouped polynomial, no contraction.
    Glibc,
    /// glibc's Shimizu-grouped polynomial with FMA contraction — the
    /// **x86-64 desktop hypothesis, confirmed at G0** (see the module docs).
    GlibcFma,
}

/// `expm1(x)` under an explicit platform hypothesis.
pub fn expm1_64_flavor(x: f64, flavor: LibmFlavor) -> f64 {
    match flavor {
        LibmFlavor::Msun => expm1_inline::<false, false>(x),
        LibmFlavor::MsunFma => expm1_inline::<false, true>(x),
        LibmFlavor::Glibc => expm1_inline::<true, false>(x),
        LibmFlavor::GlibcFma => expm1_inline::<true, true>(x),
    }
}

/// `tanh(x)` under an explicit platform hypothesis.
pub fn tanh64_flavor(x: f64, flavor: LibmFlavor) -> f64 {
    match flavor {
        LibmFlavor::Msun => tanh_inline::<false, false>(x),
        LibmFlavor::MsunFma => tanh_inline::<false, true>(x),
        LibmFlavor::Glibc => tanh_inline::<true, false>(x),
        LibmFlavor::GlibcFma => tanh_inline::<true, true>(x),
    }
}

/// `expm1(x)` — FreeBSD msun / fdlibm `s_expm1.c`, **without** FMA contraction.
pub fn expm1_64(x: f64) -> f64 {
    expm1_inline::<false, false>(x)
}

/// `expm1(x)` — msun source with the multiply-adds contracted.
pub fn expm1_64_fma(x: f64) -> f64 {
    expm1_inline::<false, true>(x)
}

/// `expm1(x)` — glibc `sysdeps/ieee754/dbl-64/s_expm1.c`, no contraction.
pub fn expm1_64_glibc(x: f64) -> f64 {
    expm1_inline::<true, false>(x)
}

/// `expm1(x)` — glibc source with FMA contraction (the x86-64 multiarch build).
pub fn expm1_64_glibc_fma(x: f64) -> f64 {
    expm1_inline::<true, true>(x)
}

#[inline(always)]
fn fma_or<const FMA: bool>(a: f64, b: f64, c: f64) -> f64 {
    if FMA {
        a.mul_add(b, c)
    } else {
        a * b + c
    }
}

#[inline]
fn expm1_inline<const GLIBC: bool, const FMA: bool>(mut x: f64) -> f64 {
    let mut hx = high_word(x);
    let xsb = hx & 0x8000_0000; // sign bit of x
    hx &= 0x7fff_ffff; // high word of |x|

    // filter out huge and non-finite argument
    if hx >= 0x4043_687A {
        // |x| >= 56*ln2
        if hx >= 0x4086_2E42 {
            // |x| >= 709.78...
            if hx >= 0x7ff0_0000 {
                if ((hx & 0xf_ffff) | low_word(x)) != 0 {
                    return x + x; // NaN
                }
                return if xsb == 0 { x } else { -1.0 }; // exp(+-inf) = {inf, -1}
            }
            if x > O_THRESHOLD {
                return HUGE * HUGE; // overflow
            }
        }
        if xsb != 0 {
            // x < -56*ln2, return -1.0 with inexact
            if x + TINY < 0.0 {
                return TINY - ONE;
            }
        }
    }

    let k: i32;
    let mut c = 0.0f64;
    // argument reduction
    if hx > 0x3fd6_2e42 {
        // |x| > 0.5 ln2
        let hi: f64;
        let lo: f64;
        if hx < 0x3FF0_A2B2 {
            // and |x| < 1.5 ln2
            if xsb == 0 {
                hi = x - LN2_HI;
                lo = LN2_LO;
                k = 1;
            } else {
                hi = x + LN2_HI;
                lo = -LN2_LO;
                k = -1;
            }
        } else {
            k = fma_or::<FMA>(INVLN2, x, if xsb == 0 { 0.5 } else { -0.5 }) as i32;
            let t = k as f64;
            hi = fma_or::<FMA>(-t, LN2_HI, x); // t*ln2_hi is exact here
            lo = t * LN2_LO;
        }
        x = hi - lo;
        c = (hi - x) - lo;
    } else if hx < 0x3c90_0000 {
        // |x| < 2**-54, return x
        let t = HUGE + x;
        return x - (t - (HUGE + x));
    } else {
        k = 0;
    }

    // x is now in primary range
    let hfx = 0.5 * x;
    let hxs = x * hfx;
    let r1 = if GLIBC {
        // glibc: R1 = 1 + hxs*Q1; h2 = hxs*hxs; R2 = Q2 + hxs*Q3; h4 = h2*h2;
        //        R3 = Q4 + hxs*Q5; r1 = R1 + h2*R2 + h4*R3;
        let rr1 = fma_or::<FMA>(hxs, Q1, ONE);
        let h2 = hxs * hxs;
        let rr2 = fma_or::<FMA>(hxs, Q3, Q2);
        let h4 = h2 * h2;
        let rr3 = fma_or::<FMA>(hxs, Q5, Q4);
        fma_or::<FMA>(h4, rr3, fma_or::<FMA>(h2, rr2, rr1))
    } else {
        // msun/fdlibm: plain Horner
        fma_or::<FMA>(
            hxs,
            fma_or::<FMA>(
                hxs,
                fma_or::<FMA>(hxs, fma_or::<FMA>(hxs, fma_or::<FMA>(hxs, Q5, Q4), Q3), Q2),
                Q1,
            ),
            ONE,
        )
    };
    let t = fma_or::<FMA>(-r1, hfx, 3.0);
    let mut e = hxs * ((r1 - t) / fma_or::<FMA>(-x, t, 6.0));
    if k == 0 {
        return x - fma_or::<FMA>(x, e, -hxs); // c is 0
    }
    let twopk = insert_words(((0x3ff + k) as u32) << 20, 0); // 2^k
    e = fma_or::<FMA>(x, e - c, -c);
    e -= hxs;
    if k == -1 {
        return 0.5 * (x - e) - 0.5;
    }
    if k == 1 {
        if x < -0.25 {
            return -2.0 * (e - (x + 0.5));
        }
        return ONE + 2.0 * (x - e);
    }
    let y: f64;
    if k <= -2 || k > 56 {
        // suffice to return exp(x) - 1
        let mut yy = ONE - (e - x);
        if k == 1024 {
            yy = yy * 2.0 * f64::from_bits(0x7FE0000000000000); // 0x1p1023
        } else {
            yy *= twopk;
        }
        return yy - ONE;
    }
    let mut t = ONE;
    if k < 20 {
        t = set_high_word(t, 0x3ff0_0000 - (0x20_0000u32 >> k)); // t = 1 - 2^-k
        y = (t - (e - x)) * twopk;
    } else {
        t = set_high_word(t, ((0x3ff - k) as u32) << 20); // t = 2^-k
        let mut yy = x - (e + t);
        yy += ONE;
        y = yy * twopk;
    }
    y
}

/// `tanh(x)` — FreeBSD msun `s_tanh.c` over the non-contracted [`expm1_64`].
pub fn tanh64(x: f64) -> f64 {
    tanh_inline::<false, false>(x)
}

/// `tanh(x)` — msun `s_tanh.c` over the FMA-contracted [`expm1_64_fma`].
pub fn tanh64_fma(x: f64) -> f64 {
    tanh_inline::<false, true>(x)
}

/// `tanh(x)` — glibc `s_tanh.c` over [`expm1_64_glibc`].
pub fn tanh64_glibc(x: f64) -> f64 {
    tanh_inline::<true, false>(x)
}

/// `tanh(x)` — glibc `s_tanh.c` over [`expm1_64_glibc_fma`].
///
/// **G0 finding (2026-07-31):** this is the flavour that reproduces glibc 2.39
/// on x86-64. The route to it: reconstructing `s_tanh` in Python over the
/// *platform's own* `expm1` matched `math.tanh` 214333/214333 on the corpus,
/// which localised the entire divergence to `expm1`; reading glibc's
/// `s_expm1.c` then showed its polynomial grouping differs from msun's.
pub fn tanh64_glibc_fma(x: f64) -> f64 {
    tanh_inline::<true, true>(x)
}

#[inline]
fn tanh_inline<const GLIBC: bool, const FMA: bool>(x: f64) -> f64 {
    let jx = high_word(x) as i32;
    let ix = jx & 0x7fff_ffff;

    // x is INF or NaN
    if ix >= 0x7ff0_0000 {
        return if jx >= 0 { ONE / x + ONE } else { ONE / x - ONE };
    }

    let z: f64;
    if ix < 0x4036_0000 {
        // |x| < 22
        if GLIBC {
            // glibc has an explicit +-0 case and a 2^-55 (not 2^-28) tiny branch
            if (ix as u32 | low_word(x)) == 0 {
                return x;
            }
            if ix < 0x3c80_0000 {
                return x * (ONE + x);
            }
        } else if ix < 0x3e30_0000 {
            // msun: |x| < 2**-28
            if HUGE + x > ONE {
                return x; // tanh(tiny) = tiny with inexact
            }
        }
        if ix >= 0x3ff0_0000 {
            // |x| >= 1
            let t = expm1_inline::<GLIBC, FMA>(2.0 * x.abs());
            z = ONE - 2.0 / (t + 2.0);
        } else {
            let t = expm1_inline::<GLIBC, FMA>(-2.0 * x.abs());
            z = -t / (t + 2.0);
        }
    } else {
        // |x| >= 22, return +-1
        z = ONE - TINY; // raise inexact flag
    }
    if jx >= 0 {
        z
    } else {
        -z
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Distance in ULPs between two finite doubles.
    fn ulp_diff(a: f64, b: f64) -> u64 {
        if a == b {
            return 0;
        }
        let ai = a.to_bits() as i64;
        let bi = b.to_bits() as i64;
        // map to a monotone ordering
        let m = |v: i64| if v < 0 { i64::MIN - v } else { v };
        (m(ai) - m(bi)).unsigned_abs()
    }

    #[test]
    fn exp_exact_special_points() {
        assert_eq!(exp64(0.0).to_bits(), 1.0f64.to_bits());
        assert_eq!(exp64(-0.0).to_bits(), 1.0f64.to_bits());
        assert_eq!(exp64(f64::NEG_INFINITY), 0.0);
        assert_eq!(exp64(f64::INFINITY), f64::INFINITY);
        assert!(exp64(f64::NAN).is_nan());
        assert_eq!(exp64(1000.0), f64::INFINITY);
        assert_eq!(exp64(-1000.0), 0.0);
    }

    #[test]
    fn exp_agrees_with_std_within_1_ulp() {
        // std's f64::exp calls the platform libm. This is a sanity band, not a
        // parity claim -- the harness makes the parity claim.
        let mut worst = 0u64;
        let mut x = -100.0f64;
        while x <= 20.0 {
            let a = exp64(x);
            let b = x.exp();
            worst = worst.max(ulp_diff(a, b));
            x += 0.0007771;
        }
        assert!(worst <= 1, "exp64 vs std worst ulp = {worst}");
    }

    #[test]
    fn exp_fma_variant_is_close_to_scalar() {
        let mut worst = 0u64;
        let mut x = -50.0f64;
        while x <= 10.0 {
            worst = worst.max(ulp_diff(exp64(x), exp64_fma(x)));
            x += 0.0013;
        }
        assert!(worst <= 1, "exp64 vs exp64_fma worst ulp = {worst}");
    }

    #[test]
    fn exp_subnormal_and_overflow_edges() {
        // Just below/above the boundaries where specialcase() engages.
        for &x in &[-745.0f64, -744.5, -708.0, -709.9, 709.0, 709.78, 709.79] {
            let a = exp64(x);
            let b = x.exp();
            assert!(ulp_diff(a, b) <= 1 || (a == b), "x={x} a={a:e} b={b:e}");
        }
    }

    #[test]
    fn tanh_exact_special_points() {
        assert_eq!(tanh64(0.0).to_bits(), 0.0f64.to_bits());
        assert_eq!(tanh64(-0.0).to_bits(), (-0.0f64).to_bits());
        assert_eq!(tanh64(f64::INFINITY), 1.0);
        assert_eq!(tanh64(f64::NEG_INFINITY), -1.0);
        assert!(tanh64(f64::NAN).is_nan());
        assert_eq!(tanh64(30.0), 1.0);
        assert_eq!(tanh64(-30.0), -1.0);
    }

    #[test]
    fn tanh_is_odd() {
        let mut x = 0.0f64;
        while x < 25.0 {
            assert_eq!(tanh64(-x).to_bits(), (-tanh64(x)).to_bits(), "x={x}");
            x += 0.00317;
        }
    }

    /// **G0 finding (2026-07-31, glibc 2.39 / x86-64).** `LibmFlavor::GlibcFma`
    /// reproduces the platform `tanh` BIT-EXACTLY; the other three flavours do
    /// not. Both axes matter and both were found by reading source, not guessing:
    /// glibc's `expm1` polynomial grouping differs from msun's, and glibc's
    /// x86-64 multiarch build contracts the multiply-adds into FMAs.
    ///
    /// This is a platform assertion, so it is skipped off glibc/x86-64 — the
    /// point of `LibmFlavor` is that the right answer differs per platform
    /// (bionic is msun-derived).
    #[test]
    fn glibc_fma_flavor_is_bit_exact_vs_platform_tanh() {
        if !cfg!(all(target_os = "linux", target_env = "gnu", target_arch = "x86_64")) {
            return;
        }
        let mut mismatches = 0usize;
        let mut worst_other = [0u64; 4];
        let mut x = -22.0f64;
        while x <= 22.0 {
            let want = x.tanh();
            if tanh64_flavor(x, LibmFlavor::GlibcFma).to_bits() != want.to_bits() {
                mismatches += 1;
            }
            for (i, fl) in [LibmFlavor::Msun, LibmFlavor::MsunFma,
                            LibmFlavor::Glibc, LibmFlavor::GlibcFma].iter().enumerate() {
                worst_other[i] = worst_other[i].max(ulp_diff(tanh64_flavor(x, *fl), want));
            }
            x += 0.000431;
        }
        assert_eq!(mismatches, 0,
                   "GlibcFma tanh should be bit-exact vs glibc; worst ulp per flavour \
                    [msun, msun_fma, glibc, glibc_fma] = {worst_other:?}");
    }

    /// Same, for the `expm1` kernel that carries the whole divergence.
    #[test]
    fn glibc_fma_flavor_is_bit_exact_vs_platform_expm1() {
        if !cfg!(all(target_os = "linux", target_env = "gnu", target_arch = "x86_64")) {
            return;
        }
        let mut mismatches = 0usize;
        let mut x = -45.0f64;
        while x <= 45.0 {
            if expm1_64_flavor(x, LibmFlavor::GlibcFma).to_bits() != x.exp_m1().to_bits() {
                mismatches += 1;
            }
            x += 0.000917;
        }
        assert_eq!(mismatches, 0, "GlibcFma expm1 should be bit-exact vs glibc");
    }

    /// The four flavours must actually be four different functions, otherwise
    /// the enum is decorative and the G0 evidence means nothing. The
    /// disagreements are rare (~1e-4 of arguments), so this needs a dense sweep.
    #[test]
    fn flavors_are_distinct_functions() {
        let all = [LibmFlavor::Msun, LibmFlavor::MsunFma,
                   LibmFlavor::Glibc, LibmFlavor::GlibcFma];
        let mut diff = [[0usize; 4]; 4];
        let mut x = -22.0f64;
        while x <= 22.0 {
            let v: Vec<u64> = all.iter().map(|f| tanh64_flavor(x, *f).to_bits()).collect();
            for i in 0..4 {
                for j in 0..4 {
                    if v[i] != v[j] {
                        diff[i][j] += 1;
                    }
                }
            }
            x += 5e-5;
        }
        for i in 0..4 {
            for j in (i + 1)..4 {
                assert!(diff[i][j] > 0,
                        "{:?} and {:?} are the same function over the sweep",
                        all[i], all[j]);
            }
        }
    }

    #[test]
    fn tanh_tiny_returns_argument() {
        let t = 1e-30f64;
        assert_eq!(tanh64(t).to_bits(), t.to_bits());
    }
}
