"""F9 / D1 — the OUR-engine <-> JCloisterZone representation map.

Everything in this module is a *relabelling*, established by the 2026-08-03 spike
(``measurement/jcz_spike_20260803/SPIKE_REPORT.md`` Q2) and re-derived here so the
replay harness never guesses. Four independent conventions have to line up:

1. **half-edges** (farm geometry) — both engines name 8 half-edges clockwise from
   the NW corner, so the map is a straight relabelling with no reflection and no
   offset (SPIKE_REPORT Q2, confirmed two ways: our patched `opposite_farmer_side`
   involution maps to JCZ's mirror-across-the-border pairs, and 31/32 tile kinds
   then match field-for-field).

2. **edges** (city / road geometry) — TOP/RIGHT/BOTTOM/LEFT <-> N/E/S/W.

3. **coordinates** — ours are ``Coordinate(row, column)`` on a 35x35 grid with the
   start tile at ``starting_position``; JCZ's are ``[x, y]`` with the start tile at
   ``[0, 0]`` and **y increasing downward** (north-negative).  So
   ``x = column - col0``, ``y = row - row0``.

4. **rotation** — both engines rotate clockwise in quarter turns, but their *base*
   orientations differ per tile kind. ``TILE_MAPPING.tsv`` records, per kind, the
   number of CW quarter turns that take OUR base orientation to JCZ's, so a tile
   we placed at ``tile.turns = t`` is JCZ's ``rotation = ((t - rot_cw90) % 4) * 90``.
   ⚠️ JCZ serialises rotation as an **int** inside ``action.options`` but as the
   **enum string ``"R180"``** inside a ``PLACE_TILE`` payload — a plain int silently
   no-ops the ply (SPIKE_REPORT A5). ``jcz_rotation_str`` is the only thing that
   should ever build that field.

5. **meeple slots** (the D1 unknown, resolved — see ``docs`` block below).

## The meeple-slot (JCZ ``location``) mapping

Our action space (``action_space.py``) offers 9 meeple slots on the just-placed
tile: NORMAL on ``{TOP, RIGHT, BOTTOM, LEFT, CENTER}`` and FARMER on the four
corners ``{TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT}``.  JCZ instead points
at a *feature*: ``{"position": [x,y], "location": "...", "feature": "City"|"Road"|
"Field"|"Monastery"}``, where ``location`` is the feature's footprint **on that
tile, in board orientation**:

| our slot | our resolution on the placed tile | JCZ ``feature`` | JCZ ``location`` |
|---|---|---|---|
| NORMAL ``TOP``/``RIGHT``/``BOTTOM``/``LEFT`` | the ``tile.city`` group, or the ``tile.road`` ``Connection``, containing that edge | ``City`` / ``Road`` | the **named edge mask** of that group's non-CENTER edges: ``"N"``, ``"WE"``, ``"NW"``, ``"NWSE"``, and the complements ``"_N".."_W"`` for a 3-edge city (see ``JCZ_EDGE_LOCATIONS``) |
| NORMAL ``CENTER`` | ``tile.chapel`` | ``Monastery`` | ``"I"`` (interior) |
| FARMER corner | the ``FarmerConnection`` whose ``farmer_positions`` contains that corner | ``Field`` | its ``tile_connections`` as JCZ half-edges, **``.``-joined** (``"EL.WR"``) |

Two structural consequences, both handled by ``jcz_location_for``/the differ:

* **Our slots are finer than JCZ's.** A city spanning TOP and RIGHT is one JCZ
  option but two of our slots, and a 3-corner field is one JCZ option but three
  of our slots. Meeple legal-sets are therefore compared **canonicalised to the
  JCZ ``(feature, location)`` key**, never slot-for-slot.
* **Token order is not meaningful.** JCZ emits a fixed order; we compare the
  parsed token *sets* (``parse_location``), so ``"WE"`` == ``"EW"``.

Provenance: ``measurement/jcz_spike_20260803/TILE_MAPPING.tsv`` (vendored with the
spike, generated by ``jcz_tile_diff.py`` against JCZ-Client ``basic.xml``); the
D0 pytest ``tests/test_jcz_tile_oracle.py`` keeps it honest.
"""
from __future__ import annotations

import csv
from pathlib import Path

from wingedsheep.carcassonne.objects.farmer_side import FarmerSide
from wingedsheep.carcassonne.objects.side import Side

# --------------------------------------------------------------------------- #
# 1. half-edges — clockwise from the NW corner, both engines                    #
# --------------------------------------------------------------------------- #
OUR_HALF_EDGES_CW: tuple[FarmerSide, ...] = (
    FarmerSide.TLT, FarmerSide.TRT, FarmerSide.TRR, FarmerSide.BRR,
    FarmerSide.BRB, FarmerSide.BLB, FarmerSide.BLL, FarmerSide.TLL,
)
JCZ_HALF_EDGES_CW: tuple[str, ...] = ("NL", "NR", "EL", "ER", "SL", "SR", "WL", "WR")

HALF_EDGE_TO_JCZ: dict[FarmerSide, str] = dict(zip(OUR_HALF_EDGES_CW, JCZ_HALF_EDGES_CW))
JCZ_TO_HALF_EDGE: dict[str, FarmerSide] = {v: k for k, v in HALF_EDGE_TO_JCZ.items()}
HALF_EDGE_SET: frozenset[str] = frozenset(JCZ_HALF_EDGES_CW)

# --------------------------------------------------------------------------- #
# 2. edges                                                                      #
# --------------------------------------------------------------------------- #
SIDE_TO_JCZ: dict[Side, str] = {
    Side.TOP: "N", Side.RIGHT: "E", Side.BOTTOM: "S", Side.LEFT: "W",
}
JCZ_TO_SIDE: dict[str, Side] = {v: k for k, v in SIDE_TO_JCZ.items()}

# --------------------------------------------------------------------------- #
# JCZ's canonical EDGE-plane location names (``Location.java``). Beware: the      #
# half-edge names (NL/NR/…) and the edge names (N/NE/_E/…) live in DIFFERENT bit  #
# planes of the same 16-bit mask, so ``N`` is NOT ``NL|NR`` and an edge location  #
# never decomposes into half-edges. JCZ prints the *registered constant* for a    #
# mask, which is why a 3-edge city comes out as ``"_E"`` ("everything but E") and #
# a straight road as ``"WE"`` — neither is parseable by splitting characters.     #
# --------------------------------------------------------------------------- #
JCZ_EDGE_LOCATIONS: dict[str, frozenset[str]] = {
    "N": frozenset("N"), "E": frozenset("E"), "S": frozenset("S"), "W": frozenset("W"),
    "NW": frozenset("NW"), "NE": frozenset("NE"),
    "SW": frozenset("SW"), "SE": frozenset("SE"),
    "WE": frozenset("WE"), "NS": frozenset("NS"),
    "NWSE": frozenset("NWSE"),
    "_N": frozenset("ESW"), "_E": frozenset("NSW"),
    "_S": frozenset("NEW"), "_W": frozenset("NES"),
}
_EDGE_TOKENS_TO_NAME: dict[frozenset[str], str] = {
    v: k for k, v in JCZ_EDGE_LOCATIONS.items()
}

#: JCZ's cloister/monastery location: the tile INTERIOR.
JCZ_MONASTERY_LOCATION = "I"
JCZ_MONASTERY_FEATURE = "Monastery"


# --------------------------------------------------------------------------- #
# 3. coordinates                                                                #
# --------------------------------------------------------------------------- #
def to_jcz_position(coord, origin_row: int, origin_col: int) -> list[int]:
    """``Coordinate(row, column)`` -> JCZ ``[x, y]`` (y grows downward/southward)."""
    return [coord.column - origin_col, coord.row - origin_row]


def from_jcz_position(pos, origin_row: int, origin_col: int) -> tuple[int, int]:
    """JCZ ``[x, y]`` -> our ``(row, column)``."""
    x, y = pos
    return (y + origin_row, x + origin_col)


# --------------------------------------------------------------------------- #
# 4. rotation                                                                   #
# --------------------------------------------------------------------------- #
def jcz_rotation_quarters(our_turns: int, rot_cw90: int) -> int:
    """Quarter turns JCZ must apply to ITS base to match our tile at ``our_turns``.

    ``rot_cw90`` (from ``TILE_MAPPING.tsv``) is how many CW quarter turns take our
    base orientation to JCZ's, i.e. ``our_base.rot(rot_cw90) == jcz_base``. A placed
    tile is ``our_base.rot(t)``; JCZ at ``j`` quarters is ``our_base.rot(rot_cw90+j)``.
    Equating gives ``j = (t - rot_cw90) mod 4``.
    """
    return (int(our_turns) - int(rot_cw90)) % 4


def jcz_rotation_str(our_turns: int, rot_cw90: int) -> str:
    """The ``"R0"|"R90"|"R180"|"R270"`` enum spelling a ``PLACE_TILE`` payload needs."""
    return "R%d" % (jcz_rotation_quarters(our_turns, rot_cw90) * 90)


# --------------------------------------------------------------------------- #
# the 32-kind table                                                             #
# --------------------------------------------------------------------------- #
TILE_MAPPING_TSV = (
    Path(__file__).resolve().parents[2]
    / "measurement" / "jcz_spike_20260803" / "TILE_MAPPING.tsv"
)


def load_tile_mapping(path: Path | str | None = None) -> dict[str, tuple[str, int]]:
    """our tile ``description`` -> ``(jcz_id, rot_cw90)``, read from the spike TSV."""
    p = Path(path) if path is not None else TILE_MAPPING_TSV
    out: dict[str, tuple[str, int]] = {}
    with p.open() as fh:
        for row in csv.DictReader(fh, delimiter="\t"):
            if not row.get("our_kind"):
                continue
            out[row["our_kind"]] = (row["jcz_id"], int(row["rot_cw90"]))
    if len(out) != 32:
        raise ValueError(f"{p}: expected 32 tile kinds, got {len(out)}")
    return out


# --------------------------------------------------------------------------- #
# 5. locations                                                                  #
# --------------------------------------------------------------------------- #
def parse_location(loc: str) -> frozenset[str]:
    """A JCZ ``location`` string -> its token set.

    Three spellings coexist and all appear in the SAME stream:
      * fields  — half-edges, ``.``-separated:  ``"EL.WR"`` -> ``{EL, WR}``
      * cities / roads — a **named edge mask** from ``JCZ_EDGE_LOCATIONS``:
        ``"WE"`` -> ``{W, E}``, ``"_E"`` -> ``{N, S, W}``, ``"NWSE"`` -> all four
      * ``"I"`` (monastery interior) -> ``{"I"}``

    Comparing token SETS (not strings) is what makes the differ insensitive to
    JCZ's emission order and to its shorthand naming.
    """
    tokens: set[str] = set()
    for part in str(loc).split("."):
        if not part:
            continue
        if part == JCZ_MONASTERY_LOCATION:
            tokens.add(part)
        elif part in HALF_EDGE_SET:
            tokens.add(part)
        elif part in JCZ_EDGE_LOCATIONS:
            tokens |= JCZ_EDGE_LOCATIONS[part]
        else:
            raise ValueError(f"unparsable JCZ location {loc!r} (token {part!r})")
    return frozenset(tokens)


def format_edge_location(sides) -> str:
    """Our edge Sides -> JCZ's canonical edge-mask name (``"WE"``, ``"_E"``, …)."""
    letters = frozenset(SIDE_TO_JCZ[s] for s in sides if s in SIDE_TO_JCZ)
    return _EDGE_TOKENS_TO_NAME.get(letters, "".join(sorted(letters)))


def format_field_location(farmer_sides) -> str:
    """Our (board-oriented) FarmerSides -> JCZ's ``.``-joined half-edge spelling."""
    labels = {HALF_EDGE_TO_JCZ[fs] for fs in farmer_sides}
    return ".".join(lbl for lbl in JCZ_HALF_EDGES_CW if lbl in labels)


def jcz_location_for(tile, side: Side) -> tuple[str, frozenset[str]] | None:
    """The ``(feature, token-set)`` a meeple on our slot ``side`` of ``tile`` means.

    ``tile`` must be the tile AS PLACED (already rotated — the board holds
    ``Tile.turn(t)``, whose ``city`` / ``road`` / ``farms`` are all in board
    orientation), so no rotation math happens here.

    Returns ``None`` when the slot is not a legal meeple target on this tile,
    which is how an unmappable slot is surfaced rather than guessed.
    """
    if side == Side.CENTER:
        return (JCZ_MONASTERY_FEATURE, frozenset({JCZ_MONASTERY_LOCATION})) if tile.chapel else None

    if side in (Side.TOP_LEFT, Side.TOP_RIGHT, Side.BOTTOM_LEFT, Side.BOTTOM_RIGHT):
        for fc in (tile.farms or ()):
            if side in fc.farmer_positions:
                return ("Field", frozenset(HALF_EDGE_TO_JCZ[fs] for fs in fc.tile_connections))
        return None

    if side in SIDE_TO_JCZ:
        for group in (tile.city or ()):
            if side in group:
                return ("City", frozenset(SIDE_TO_JCZ[s] for s in group))
        for conn in (tile.road or ()):
            if side in (conn.a, conn.b):
                edges = {s for s in (conn.a, conn.b) if s in SIDE_TO_JCZ}
                return ("Road", frozenset(SIDE_TO_JCZ[s] for s in edges))
        return None

    return None
